name: debug

on: workflow_dispatch

env:
  MAX_VERSIONS: 10

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        id: step1
        run: |
          echo "COUNT=3" >> GITHUB_OUTPUT
      - name: step2
        run: |
          echo "COUNT: ${{ steps.step1.outputs.COUNT }}"
          echo "MAX_VERSIONS: ${{ env.MAX_VERSIONS }}"

    