name: debug

on: workflow_dispatch

env:
  MAX_VERSIONS: 1

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        id: step1
        run: |
          echo "COUNT=3" >> $GITHUB_OUTPUT
      - name: step2
        run: |
          echo "COUNT (output): ${{ steps.step1.outputs.COUNT }}"
          if [ ${{ steps.step1.outputs.COUNT }} -ge ${{ env.MAX_VERSIONS }} ]
          then
            echo "TOO_MANY=true" >> $GITHUB_ENV
          else
            echo "TOO_MANY=false" >> $GITHUB_ENV
          fi
      - name: ech check result
        run: |
          echo "${{ env.TOO_MANY }}"
      - name: check 
        if: ${{  env.TOO_MANY == true }}
        run: |
          echo "Too many versions"
          exit 1
          


    