name: debug

on: workflow_dispatch

env:
  MAX_VERSIONS: 1

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        id: step1
        run: |
          COUNT=3
          echo "COUNT=$COUNT" >> $GITHUB_OUTPUT
          if [ $COUNT -ge ${{ env.MAX_VERSIONS }} ]
          then
            echo "TOO_MANY=true" >> $GITHUB_ENV
          else
            echo "TOO_MANY=false" >> $GITHUB_ENV
          fi
      - name: echo variables
        run: |
          echo "COUNT (output): ${{ steps.step1.outputs.COUNT }}"
          echo "TOO_MANY (output): ${{ env.TOO_MANY }}"
      - name: check 
        if: ${{  env.TOO_MANY == 'true' }}
        run: |
          echo "Too many versions"
          exit 1
          


    