name: debug

on: workflow_dispatch

env:
  MAX_VERSIONS: 10

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        id: step1
        run: |
          echo "COUNT=3" >> $GITHUB_OUTPUT
          echo "COUNT=3" >> $GITHUB_ENV
      - name: step2
        run: |
          echo "COUNT (output): ${{ steps.step1.outputs.COUNT }}"
          echo "COUNT (env): ${{ env.COUNT }}"
          echo "MAX_VERSIONS: ${{ env.MAX_VERSIONS }}"
      - name: echo check result
        run: |
          echo "${{  steps.step1.outputs.COUNT >= env.MAX_VERSIONS }}"
      - name: check 1 
        if: ${{  steps.step1.outputs.COUNT >= env.MAX_VERSIONS }}
        run: |
          echo "Too many versions"
          


    