name: remove

on:
  workflow_dispatch

jobs: 

  remove: 
    name: Remove
    runs-on: ubuntu-latest

    steps: 
      - name: config
        id: config
        run: |
          echo ${{ github.ref }}
          echo ${{ github.sha }}
    
    



  