name: remove

on:
  workflow_dispatch

jobs: 

  config: 
    runs-on: ubuntu-latest
    outputs: 
      tag: ${{ steps.tag.outputs.TAG }}
      stage: ${{ steps.stage.outputs.STAGE }}
    
    steps: 
      - name: Identify tag
        id: tag
        run: |
          echo TAG=$(echo ${{ github.ref }} | sed -e "s/^refs\/tags\///")>> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check existence of the version and fetch the associated stage
        id: stage
        run: | 
          echo STAGE=$(aws ssm get-parameter --name fnd-api-s2-versions --query "Parameter.Value" --output text | jq -e  '.[] | select(.tag == "${{ steps.tag.outputs.TAG }}") | .stage') >> $GITHUB_OUTPUT

      - name: Check STAGE variable
        if: steps.stage.outputs.STAGE  == null
        run: |
           echo ${{ steps.stage.outputs.STAGE }}
           exit 1

  remove: 
    runs-on: ubuntu-latest
    needs: config

    steps: 
      - name: Check workflow run
        run: |
          echo ${{ needs.config.outputs.stage }}
          echo ${{ needs.config.outputs.tag }} 








